// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WahaSender.Api.Data;

#nullable disable

namespace WahaSender.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526141134_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("WahaSender.Api.Entities.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayMaxSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayMinSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactorIncremento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteDiarioActual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ModoEnvioActivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WahaApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("WahaEndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WahaSession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DelayMaxSegundos = 45,
                            DelayMinSegundos = 15,
                            FactorIncremento = 5,
                            LimiteDiarioActual = 50,
                            ModoEnvioActivo = false,
                            WahaApiKey = "119ce04a85dd41818809be61aba87066",
                            WahaEndpointUrl = "http://localhost:3000/api/sendText",
                            WahaSession = "default"
                        });
                });

            modelBuilder.Entity("WahaSender.Api.Entities.DetalleEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajeAsignado")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajeError")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WahaAckCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("LoteId");

                    b.HasIndex("Estado", "FechaProcesado");

                    b.ToTable("DetallesEnvios");
                });

            modelBuilder.Entity("WahaSender.Api.Entities.LoteEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LotesEnvios");
                });

            modelBuilder.Entity("WahaSender.Api.Entities.PlantillaMensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuerpoTexto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Indice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlantillasMensajes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CuerpoTexto = "💰 ¡Crédito aprobado a sola firma!\nHola {Nombre}, solo con tu DNI puedes acceder a tu préstamo inmediato.\n\n👩‍💼 Ejecutiva: Betty Farroñan\n📲 995799743",
                            Indice = 1,
                            Tipo = "prestamo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CuerpoTexto = "💰 Banco Santander tiene un préstamo pre-aprobado para ti, {Nombre}.\nAccede rápido, sin papeleos y con tu DNI.\n\n👩‍💼 Ejecutiva: Betty Farroñan\n📲 995799743",
                            Indice = 2,
                            Tipo = "prestamo"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CuerpoTexto = "💰 ¡Tu oportunidad está aquí, {Nombre}!\nPréstamo personal disponible con aprobación inmediata. Solo necesitas tu DNI.\n\n👩‍💼 Ejecutiva: Betty Farroñan\n📲 995799743",
                            Indice = 3,
                            Tipo = "prestamo"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CuerpoTexto = "💳 ¡Ya tienes tu tarjeta Santander aprobada, {Nombre}!\nDisfruta beneficios exclusivos y compras sin intereses.\n\n👩‍💼 Ejecutiva: Betty Farroñan\n📲 995799743",
                            Indice = 4,
                            Tipo = "tarjeta"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CuerpoTexto = "💳 Banco Santander te ofrece tarjeta de crédito con aprobación inmediata, {Nombre}.\nEmpieza a disfrutar descuentos y facilidades hoy.\n\n👩‍💼 Ejecutiva: Betty Farroñan\n📲 995799743",
                            Indice = 5,
                            Tipo = "tarjeta"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CuerpoTexto = "💳 ¡Activa y disfruta tu tarjeta Santander VISA, {Nombre}!\nAprovecha promociones y meses sin intereses.\n\n👩‍💼 Ejecutiva: Betty Farroñan\n📲 995799743",
                            Indice = 6,
                            Tipo = "tarjeta"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CuerpoTexto = "👋 Hola {Nombre}, tienes beneficios disponibles en Banco Santander.\nPuedes acceder a préstamo o tarjeta con tu DNI.\n\n👩‍💼 Ejecutiva: Betty Farroñan\n📲 995799743",
                            Indice = 7,
                            Tipo = "bienvenida"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CuerpoTexto = "👋 Banco Santander te da la bienvenida, {Nombre}.\nTienes opciones de crédito disponibles listas para ti.\n\n👩‍💼 Ejecutiva: Betty Farroñan\n📲 995799743",
                            Indice = 8,
                            Tipo = "bienvenida"
                        });
                });

            modelBuilder.Entity("WahaSender.Api.Entities.DetalleEnvio", b =>
                {
                    b.HasOne("WahaSender.Api.Entities.LoteEnvio", "Lote")
                        .WithMany("Detalles")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("WahaSender.Api.Entities.LoteEnvio", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
