// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WahaSender.Api.Data;

#nullable disable

namespace WahaSender.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529045127_AddDocumentoYNoRegistrado")]
    partial class AddDocumentoYNoRegistrado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("WahaSender.Api.Entities.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayMaxSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayMinSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactorIncremento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteDiarioActual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ModoEnvioActivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WahaApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("WahaEndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WahaSession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DelayMaxSegundos = 45,
                            DelayMinSegundos = 15,
                            FactorIncremento = 5,
                            LimiteDiarioActual = 50,
                            ModoEnvioActivo = false,
                            WahaApiKey = "119ce04a85dd41818809be61aba87066",
                            WahaEndpointUrl = "http://localhost:3000/api/sendText",
                            WahaSession = "default"
                        });
                });

            modelBuilder.Entity("WahaSender.Api.Entities.DetalleEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsNumeroNoRegistrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajeAsignado")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajeError")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WahaAckCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EsNumeroNoRegistrado");

                    b.HasIndex("Estado");

                    b.HasIndex("LoteId");

                    b.HasIndex("Estado", "FechaProcesado");

                    b.ToTable("DetallesEnvios");
                });

            modelBuilder.Entity("WahaSender.Api.Entities.LoteEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LotesEnvios");
                });

            modelBuilder.Entity("WahaSender.Api.Entities.PlantillaMensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuerpoTexto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Indice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlantillasMensajes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CuerpoTexto = "✨ ¡Hola, {Nombre}! Qué alegría saludarte. Te escribe *Betty Farroñan*, tu asesora de Banco Santander.\n\nTe comparto una excelente noticia: con una única evaluación de tu DNI, tienes aprobada una *Tarjeta de Crédito* llena de beneficios exclusivos y un *Préstamo Personal* de libre disponibilidad. 🚀\n\nTodo el trámite es 100% digital, rápido y seguro.\n\n¿Te gustaría conocer el límite de tu tarjeta y el monto de tu préstamo?\n\n👩‍💼 Ejecutiva: *Betty Farroñan*\n👉 Confirma aquí: https://wa.link/xe4ext  o 995799743",
                            Indice = 1,
                            Tipo = "prestamo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CuerpoTexto = "🌟 Estimado/a {Nombre}, espero que tengas un día excelente. Soy *Betty Farroñan*.\n\nQueremos premiar tu buen historial. Solo con tu DNI, Banco Santander te ha pre-aprobado un *Préstamo Personal* para lo que necesites, además de una *Tarjeta de Crédito* con descuentos preferenciales. 💳💰\n\nAmbos productos están listos para ser activados sin papeleos.\n\n¿Me permites brindarte los detalles para coordinar la entrega?\n\n👩‍💼 Ejecutiva: *Betty Farroñan*\n👉 Escríbeme aquí: https://wa.link/xe4ext o 995799743",
                            Indice = 2,
                            Tipo = "prestamo"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CuerpoTexto = "💎 ¡Hola, {Nombre}! Soy *Betty Farroñan* de Banco Santander.\n\n¡Tu evaluación fue un éxito! Solo presentando tu DNI, has calificado para nuestra campaña VIP: una *Tarjeta de Crédito Santander* y un *Préstamo en Efectivo* inmediato. 🏆\n\nEs la oportunidad perfecta para ordenar tus finanzas y disfrutar de promociones únicas.\n\n¿Te gustaría validar tus montos aprobados en línea?\n\n👩‍💼 Ejecutiva: *Betty Farroñan*\n👉 Solicítalo aquí: https://wa.link/xe4ext o 995799743",
                            Indice = 3,
                            Tipo = "prestamo"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CuerpoTexto = "🎉 Buen día, {Nombre}. Qué gusto saludarte, soy *Betty Farroñan*.\n\nHoy tienes acceso a una oferta doble e irrepetible: *Préstamo Personal* con tasa preferencial + *Tarjeta de Crédito*, ¡ambos aprobados con una única evaluación de tu DNI! 💼💳\n\nCero trámites engorrosos, todo es digital y seguro.\n\n¿Prefieres que te envíe la información por este medio o agendamos una llamada corta?\n\n👩‍💼 Ejecutiva: *Betty Farroñan*\n👉 Contáctame aquí: https://wa.link/xe4ext o 995799743",
                            Indice = 4,
                            Tipo = "prestamo"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CuerpoTexto = "🥇 ¡Hola, {Nombre}! Te saluda *Betty Farroñan*, tu ejecutiva Santander.\n\nTengo grandes noticias para ti: gracias a nuestra evaluación ágil (solo con tu DNI), has desbloqueado dos productos exclusivos:\n✅ *Tarjeta de Crédito* (con exoneración de membresía sujeta a uso).\n✅ *Préstamo Personal* (liquidez inmediata a tu cuenta).\n\nEstán listos para ti. ¿Coordinamos la entrega de tu tarjeta a domicilio sin costo?\n\n👩‍💼 Ejecutiva: *Betty Farroñan*\n👉 Escríbeme aquí: https://wa.link/xe4ext o 995799743",
                            Indice = 5,
                            Tipo = "tarjeta"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CuerpoTexto = "🌟 {Nombre}, ¡tienes una oportunidad exclusiva esperándote! Soy *Betty Farroñan*.\n\nTu perfil ha sido seleccionado por Banco Santander. Con una única validación de tu DNI, te otorgamos una *Tarjeta de Crédito* para tus compras diarias y un *Préstamo Efectivo* para concretar tus proyectos. 🚀💳\n\n¡Sin trámites extras!\n\n¿Te interesa que revisemos el simulador de cuotas y los beneficios de tu tarjeta?\n\n👩‍💼 *Betty Farroñan*\n👉 Confirma aquí: https://wa.link/xe4ext o 995799743",
                            Indice = 6,
                            Tipo = "tarjeta"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CuerpoTexto = "💳 ¡Hola, {Nombre}! Espero que estés genial. Te escribe *Betty Farroñan*.\n\nQueremos facilitarte la vida. Por eso, con solo verificar tu DNI, Santander te ha aprobado un *Préstamo Personal* y una nueva *Tarjeta de Crédito*. 💰✨\n\nAmbos productos te brindarán el respaldo financiero que mereces.\n\n¿A qué hora te viene bien que te explique cómo activar tus beneficios hoy mismo?\n\n👩‍💼 Ejecutiva: *Betty Farroñan*\n👉 Escríbeme aquí: https://wa.link/xe4ext o 995799743",
                            Indice = 7,
                            Tipo = "tarjeta"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CuerpoTexto = "💎 Buen día, {Nombre}. Es un placer saludarte. Soy *Betty Farroñan*, de Santander.\n\nNos complace invitarte a nuestra campaña Premium. Con una sola evaluación de tu DNI, tienes acceso inmediato a una *Tarjeta de Crédito* con bonos de bienvenida y a un *Préstamo Personal* con desembolso ágil. 🌟\n\nDisfruta de la tranquilidad de un respaldo total.\n\n¿Te gustaría que validemos tus datos de forma segura para gestionar la entrega?\n\n👩‍💼 Ejecutiva: *Betty Farroñan*\n👉 Escríbeme aquí: https://wa.link/xe4ext  o 995799743",
                            Indice = 8,
                            Tipo = "tarjeta"
                        });
                });

            modelBuilder.Entity("WahaSender.Api.Entities.DetalleEnvio", b =>
                {
                    b.HasOne("WahaSender.Api.Entities.LoteEnvio", "Lote")
                        .WithMany("Detalles")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("WahaSender.Api.Entities.LoteEnvio", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
